tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
  - name: Start web server
    init: python -m http.server 8000
ports:
  - port: 8000
    onOpen: open-preview